// Layer 3 - Base + Layer2 and Layer2 + Layer2 combinations
export const LAYER3_ELEMENTS = {
  // ===== Base + Layer2 =====
  geyser: { id: 'geyser', name: 'Geyser', emoji: '⛲', recipe: ['water', 'steam'] },
  cloud: { id: 'cloud', name: 'Cloud', emoji: '☁️', recipe: ['wind', 'steam'] },
  boil: { id: 'boil', name: 'Boil', emoji: '🫧', recipe: ['fire', 'steam'] },
  hotspring: { id: 'hotspring', name: 'Hot Spring', emoji: '♨️', recipe: ['earth', 'steam'] },
  brick: { id: 'brick', name: 'Brick', emoji: '🧱', recipe: ['fire', 'mud'] },
  swamp: { id: 'swamp', name: 'Swamp', emoji: '🐸', recipe: ['water', 'mud'] },
  clay: { id: 'clay', name: 'Clay', emoji: '🏺', recipe: ['earth', 'mud'] },
  erosion: { id: 'erosion', name: 'Erosion', emoji: '🌬️', recipe: ['wind', 'mud'] },
  plant: { id: 'plant', name: 'Plant', emoji: '🌱', recipe: ['earth', 'rain'] },
  rainbow: { id: 'rainbow', name: 'Rainbow', emoji: '🌈', recipe: ['fire', 'rain'] },
  pond: { id: 'pond', name: 'Pond', emoji: '🪷', recipe: ['water', 'rain'] },
  mist: { id: 'mist', name: 'Mist', emoji: '🌫️', recipe: ['wind', 'rain'] },
  volcano: { id: 'volcano', name: 'Volcano', emoji: '🌋', recipe: ['earth', 'lava'] },
  stone: { id: 'stone', name: 'Stone', emoji: '🪨', recipe: ['water', 'lava'] },
  inferno: { id: 'inferno', name: 'Inferno', emoji: '🔥', recipe: ['fire', 'lava'] },
  ash: { id: 'ash', name: 'Ash', emoji: '⬛', recipe: ['wind', 'lava'] },
  fog: { id: 'fog', name: 'Fog', emoji: '🌁', recipe: ['water', 'smoke'] },
  ember: { id: 'ember', name: 'Ember', emoji: '🔴', recipe: ['fire', 'smoke'] },
  pollution: { id: 'pollution', name: 'Pollution', emoji: '🏭', recipe: ['earth', 'smoke'] },
  haze: { id: 'haze', name: 'Haze', emoji: '😶‍🌫️', recipe: ['wind', 'smoke'] },
  silt: { id: 'silt', name: 'Silt', emoji: '🟤', recipe: ['water', 'dust'] },
  spark: { id: 'spark', name: 'Spark', emoji: '✨', recipe: ['fire', 'dust'] },
  sand: { id: 'sand', name: 'Sand', emoji: '🏖️', recipe: ['earth', 'dust'] },
  sandstorm: { id: 'sandstorm', name: 'Sandstorm', emoji: '🏜️', recipe: ['wind', 'dust'] },
  island: { id: 'island', name: 'Island', emoji: '🏝️', recipe: ['earth', 'ocean'] },
  wave: { id: 'wave', name: 'Wave', emoji: '🌊', recipe: ['wind', 'ocean'] },
  salt: { id: 'salt', name: 'Salt', emoji: '🧂', recipe: ['fire', 'ocean'] },
  fish: { id: 'fish', name: 'Fish', emoji: '🐟', recipe: ['water', 'ocean'] },
  light: { id: 'light', name: 'Light', emoji: '💡', recipe: ['wind', 'energy'] },
  electricity: { id: 'electricity', name: 'Electricity', emoji: '⚡', recipe: ['water', 'energy'] },
  explosion: { id: 'explosion', name: 'Explosion', emoji: '💥', recipe: ['fire', 'energy'] },
  earthquake: { id: 'earthquake', name: 'Earthquake', emoji: '🌍', recipe: ['earth', 'energy'] },
  river: { id: 'river', name: 'River', emoji: '🏞️', recipe: ['water', 'mountain'] },
  forge: { id: 'forge', name: 'Forge', emoji: '⚒️', recipe: ['fire', 'mountain'] },
  peak: { id: 'peak', name: 'Peak', emoji: '🗻', recipe: ['earth', 'mountain'] },
  cave: { id: 'cave', name: 'Cave', emoji: '🕳️', recipe: ['wind', 'mountain'] },
  snow: { id: 'snow', name: 'Snow', emoji: '❄️', recipe: ['water', 'storm'] },
  lightning: { id: 'lightning', name: 'Lightning', emoji: '⚡', recipe: ['fire', 'storm'] },
  hail: { id: 'hail', name: 'Hail', emoji: '🧊', recipe: ['earth', 'storm'] },
  tornado: { id: 'tornado', name: 'Tornado', emoji: '🌪️', recipe: ['wind', 'storm'] },

  // ===== Layer2 + Layer2 =====
  vapor: { id: 'vapor', name: 'Vapor', emoji: '💭', recipe: ['steam', 'steam'] },
  thermal: { id: 'thermal', name: 'Thermal', emoji: '🌡️', recipe: ['steam', 'mud'] },
  humidity: { id: 'humidity', name: 'Humidity', emoji: '💦', recipe: ['steam', 'rain'] },
  vent: { id: 'vent', name: 'Vent', emoji: '🕳️', recipe: ['steam', 'lava'] },
  smolder: { id: 'smolder', name: 'Smolder', emoji: '🔥', recipe: ['steam', 'smoke'] },
  murk: { id: 'murk', name: 'Murk', emoji: '🌫️', recipe: ['steam', 'dust'] },
  tropical: { id: 'tropical', name: 'Tropical', emoji: '🏝️', recipe: ['steam', 'ocean'] },
  turbine: { id: 'turbine', name: 'Turbine', emoji: '⚙️', recipe: ['steam', 'energy'] },
  fumarole: { id: 'fumarole', name: 'Fumarole', emoji: '💨', recipe: ['steam', 'mountain'] },
  weather: { id: 'weather', name: 'Weather', emoji: '🌤️', recipe: ['steam', 'storm'] },

  bog: { id: 'bog', name: 'Bog', emoji: '🐊', recipe: ['mud', 'mud'] },
  life: { id: 'life', name: 'Life', emoji: '🧬', recipe: ['mud', 'rain'] },
  adobe: { id: 'adobe', name: 'Adobe', emoji: '🧱', recipe: ['mud', 'lava'] },
  smudge: { id: 'smudge', name: 'Smudge', emoji: '⬛', recipe: ['mud', 'smoke'] },
  loam: { id: 'loam', name: 'Loam', emoji: '🟫', recipe: ['mud', 'dust'] },
  marsh: { id: 'marsh', name: 'Marsh', emoji: '🌿', recipe: ['mud', 'ocean'] },
  quicksand: { id: 'quicksand', name: 'Quicksand', emoji: '⚠️', recipe: ['mud', 'energy'] },
  landslide: { id: 'landslide', name: 'Landslide', emoji: '🏔️', recipe: ['mud', 'mountain'] },
  flood: { id: 'flood', name: 'Flood', emoji: '🌊', recipe: ['mud', 'storm'] },

  downpour: { id: 'downpour', name: 'Downpour', emoji: '🌧️', recipe: ['rain', 'rain'] },
  basalt: { id: 'basalt', name: 'Basalt', emoji: '🪨', recipe: ['rain', 'lava'] },
  acid_rain: { id: 'acid_rain', name: 'Acid Rain', emoji: '☢️', recipe: ['rain', 'smoke'] },
  slurry: { id: 'slurry', name: 'Slurry', emoji: '🥣', recipe: ['rain', 'dust'] },
  monsoon: { id: 'monsoon', name: 'Monsoon', emoji: '🌧️', recipe: ['rain', 'ocean'] },
  tempest: { id: 'tempest', name: 'Tempest', emoji: '⛈️', recipe: ['rain', 'energy'] },
  waterfall: { id: 'waterfall', name: 'Waterfall', emoji: '💧', recipe: ['rain', 'mountain'] },
  deluge: { id: 'deluge', name: 'Deluge', emoji: '🌊', recipe: ['rain', 'storm'] },

  magma: { id: 'magma', name: 'Magma', emoji: '🔶', recipe: ['lava', 'lava'] },
  sulfur: { id: 'sulfur', name: 'Sulfur', emoji: '🟡', recipe: ['lava', 'smoke'] },
  scoria: { id: 'scoria', name: 'Scoria', emoji: '🪨', recipe: ['lava', 'dust'] },
  obsidian: { id: 'obsidian', name: 'Obsidian', emoji: '🖤', recipe: ['lava', 'ocean'] },
  flare: { id: 'flare', name: 'Flare', emoji: '☀️', recipe: ['lava', 'energy'] },
  eruption: { id: 'eruption', name: 'Eruption', emoji: '🌋', recipe: ['lava', 'mountain'] },
  firestorm: { id: 'firestorm', name: 'Firestorm', emoji: '🔥', recipe: ['lava', 'storm'] },

  fumes: { id: 'fumes', name: 'Fumes', emoji: '💨', recipe: ['smoke', 'smoke'] },
  smog: { id: 'smog', name: 'Smog', emoji: '😶‍🌫️', recipe: ['smoke', 'dust'] },
  sea_smoke: { id: 'sea_smoke', name: 'Sea Smoke', emoji: '🌫️', recipe: ['smoke', 'ocean'] },
  signal: { id: 'signal', name: 'Signal', emoji: '📡', recipe: ['smoke', 'energy'] },
  volcanic_vent: { id: 'volcanic_vent', name: 'Volcanic Vent', emoji: '🌋', recipe: ['smoke', 'mountain'] },
  pyroclastic: { id: 'pyroclastic', name: 'Pyroclastic', emoji: '🌋', recipe: ['smoke', 'storm'] },

  dune: { id: 'dune', name: 'Dune', emoji: '🏜️', recipe: ['dust', 'dust'] },
  sediment: { id: 'sediment', name: 'Sediment', emoji: '🟤', recipe: ['dust', 'ocean'] },
  static: { id: 'static', name: 'Static', emoji: '⚡', recipe: ['dust', 'energy'] },
  scree: { id: 'scree', name: 'Scree', emoji: '🪨', recipe: ['dust', 'mountain'] },
  dust_devil: { id: 'dust_devil', name: 'Dust Devil', emoji: '🌪️', recipe: ['dust', 'storm'] },

  abyss: { id: 'abyss', name: 'Abyss', emoji: '🌊', recipe: ['ocean', 'ocean'] },
  current: { id: 'current', name: 'Current', emoji: '🌀', recipe: ['ocean', 'energy'] },
  glacier: { id: 'glacier', name: 'Glacier', emoji: '🧊', recipe: ['ocean', 'mountain'] },
  tsunami: { id: 'tsunami', name: 'Tsunami', emoji: '🌊', recipe: ['ocean', 'storm'] },

  plasma: { id: 'plasma', name: 'Plasma', emoji: '✨', recipe: ['energy', 'energy'] },
  geothermal: { id: 'geothermal', name: 'Geothermal', emoji: '♨️', recipe: ['energy', 'mountain'] },
  supercell: { id: 'supercell', name: 'Supercell', emoji: '⛈️', recipe: ['energy', 'storm'] },

  range: { id: 'range', name: 'Range', emoji: '🏔️', recipe: ['mountain', 'mountain'] },
  avalanche: { id: 'avalanche', name: 'Avalanche', emoji: '❄️', recipe: ['mountain', 'storm'] },

  hurricane: { id: 'hurricane', name: 'Hurricane', emoji: '🌀', recipe: ['storm', 'storm'] },
};
